### ISSUE TITLE
Import Errors

### ISSUE THREAD

**Issue by rickjunli** [vitruvianscience/OpenDeep#20]
Hi!
I just installed OpenDeep for a workshop at the OSDC, but I am getting some importing errors:

ImportError: cannot import name DenoisingAutoencoder
ImportError: cannot import name SoftmaxLayer

Do you have any suggestions as to what I am doing wrong? 

Thanks,
Rick

**Comment by vitruvianscience** [comment]
Are you on the latest master branch? What file/line is the import happening (they should have been removed)?

**Comment by rickjunli** [comment]
I followed the installation instructions 

cd opendeep
python setup.py develop

pip install -r requirements.txt

the installation went fine and I received no errors. 

which file/line should have been removed? sorry not sure i understand the question.

**Comment by mbeissinger** [comment]
Ok I just did a search in the repository and no internal files are trying to import DenoisingAutoencoder or SoftmaxLayer - are you trying to do the quickstart guide from the readme file? It is out of date since we just had a refactoring. All of the docs compiled from docstrings are current though (in the docs directory). If you want an example 'hello world' here it is:

import theano.tensor as T
from opendeep import config_root_logger
from opendeep.data import MNIST
from opendeep.models import Prototype, Dense, Softmax
from opendeep.optimization.loss import Neg_LL
from opendeep.optimization import AdaDelta

# shows debugging statements so you can see what is being created under the hood
config_root_logger()

print("Getting data...")
# data wrapper for mnist handwritten digits - an iterable stream of images that have shape (784, )
data = MNIST()

print("Creating MLP model...")
# create a Prototype container to add layers sequentially (like Torch's Sequential interface)
mlp = Prototype()
# we need to define Theano variable and any known dimension shapes for the input to the model (use None if you don't know the shape beforehand)
in_shape = (None, 784)
in_var = T.matrix('xs')
mlp.add(Dense(inputs=(in_shape, in_var), outputs=512, activation='relu'))
# now, we can add layers without specifying `inputs=` to automatically hook to outputs from previous layer. to do this we need to give the class type as first argument and any other kwargs for initializing it.
mlp.add(Dense, outputs=512, activation='relu')
mlp.add(Softmax, outputs=10, out_as_probs=False)

print("Training...")
target_var = T.lvector('ys')
loss = Neg_LL(inputs=mlp.models[-1].p_y_given_x, targets=target_var, one_hot=False)
optimizer = AdaDelta(model=mlp, dataset=data, loss=loss, epochs=10)
optimizer.train()

print("Predicting...")
preds = mlp.run(data.test_inputs)
print("Accuracy: ", float(sum(preds=data.test_targets)) / len(data.test_targets))

**Comment by mbeissinger** [comment]
Forgot styling in comments from markdown is default - every bold section is a comment starting with \# (which renders a header in markdown)

**Comment by rickjunli** [comment]
got it. I was just trying to make sure that my installation was correct and it works before the workshop. I didn't realize that part of the example code was out-of-date. thanks for clarifying!

**Comment by vitruvianscience** [comment]
good to hear! just pushed the changes to the readme.
