### ISSUE TITLE
multivariate time series example

### ISSUE THREAD

**Issue by andrewcz** [vitruvianscience/OpenDeep#24]
Hi!
Great library!!
Was wondering if there were plans for a multivariate time series example.
For a multi sequence vectors to predict a single sequence output.
ie Time series prediction with multiple sequences input mapped to a single output.
Many thanks,
Best,
Andrew

**Comment by vitruvianscience** [comment]
Thanks! Yes you can do this with recurrent nets (I'd recommend LSTM to start) - have one for each independent sequence and route their ending hidden representation state as the inputs to your classification layer:

import theano.tensor as T
from opendeep.models import LSTM, Softmax
lstm1 = LSTM(inputs=((batch_size, sequence_length), T.matrix('input1')), hiddens=num_hiddens, ...rest_of_params)
lstm2 = LSTM(inputs=((batch_size, sequence2_length), T.matrix('input2')), hiddens=num_hiddens, ...rest_of_params)
classification_input = lstm1.get_outputs()[-1] + lstm2.get_outputs()[-1]  # output is the sequence of hidden states (3d tensor with shape: [sequence_len, batch_size, hidden_size]) so we take the last hidden state. If your hidden sizes are different, you can combine them with concatenation rather than addition. This also assumes your batch sizes are the same.
softmax = Softmax(inputs=(lstm1.output_size, classification_input), outputs=num_classes, ...rest_of_params)

Let me know if this helps!
