### ISSUE TITLE
An example to use a custom data  with a predefined model

### ISSUE THREAD

**Issue by erogol** [vitruvianscience/OpenDeep#3]
Would you provide an example to use simply a numpy array as a input to predefined model?

**Comment by vitruvianscience** [comment]
I'll write up something later today, but in the meantime you can look at opendeep.data.dataset.MemoryDataset. You initialize it with train_X and optional train_Y, valid_X, valid_Y, test_X, and test_Y. These can be numpy arrays or any other array-like structure, since they get cast into numpy arrays.

**Comment by erogol** [comment]
Good thx

**Comment by vitruvianscience** [comment]
Added it to the 'First Steps' tutorial because it seems important to know in the beginning :)
http://www.opendeep.org/v0.0.5/docs/tutorial-first-steps
